---
- name: "Install packages"
  notify: "Enable and start Fail2ban"
  retries: 3
  delay: 10
  until: "output is success"
  ansible.builtin.package:
    update_cache: true
    name:
      - "fail2ban"
      - "iptables"

- name: "Configure Fail2ban"
  notify: "Restart Fail2ban"
  when: install_fail2ban__ssh_port | default(false)
  block:
    - name: "Copy jail.local configuration file"
      ansible.builtin.template:
        src: "templates/jail.local.j2"
        dest: "/etc/fail2ban/jail.local"
        owner: "root"
        group: "root"
        mode: "0600"

    - name: "Check if a /var/log/auth.log file exist"
      register: log_file
      ansible.builtin.stat:
        path: "/var/log/auth.log"

    - name: "Create a /var/log/auth.log file"
      when: not log_file.stat.exists
      ansible.builtin.file:
        path: "/var/log/auth.log"
        state: touch
        owner: "root"
        group: "root"
        mode: "0700"
