---
- name: "Install packages"
  notify: "Enable and start Fail2ban"
  ansible.builtin.package:
    update_cache: true
    name:
      - fail2ban
      - iptables

- name: "Copy jail.local configuration file"
  notify: "Restart Fail2ban"
  when: fail2ban_ssh_port
  ansible.builtin.template:
    src: "templates/jail.local.j2"
    dest: "/etc/fail2ban/jail.local"
    owner: "root"
    group: "root"
    mode: 0600
