---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.install_fail2ban"
      tags:
        - "labocbz.install_fail2ban"
      vars:
        install_fail2ban__report_email_address: "{{ inv_install_fail2ban__report_email_address }}"
        install_fail2ban__ssh_port: "{{ inv_install_fail2ban__ssh_port }}"
      ansible.builtin.include_role:
        name: "labocbz.install_fail2ban"
